/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_api_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Case */
        patch: operations["update_case_api_v1_cases__case_id__patch"];
        trace?: never;
    };
    "/api/v1/cases/{case_id}/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Complaint */
        post: operations["add_complaint_api_v1_cases__case_id__complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the service is up. Used by CI, Compose, and uptime checks.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Trace */
        post: operations["start_trace_api_v1_trace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_v1_trace__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace/{trace_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Graph */
        get: operations["get_trace_graph_api_v1_trace__trace_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace/{trace_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_trace__trace_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace/{trace_id}/sahyog-notice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sahyog Notice */
        post: operations["create_sahyog_notice_api_v1_trace__trace_id__sahyog_notice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the service is up. Used by CI, Compose, and uptime checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddComplaintRequest */
        AddComplaintRequest: {
            /**
             * Is Demo
             * @default true
             */
            is_demo: boolean;
            /** @default manual */
            source: components["schemas"]["ComplaintSource"];
            /** Text */
            text: string;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Role */
            actor_role: string | null;
            /** Address */
            address: string | null;
            /** Case Id */
            case_id: string | null;
            /** Chain */
            chain: string | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /** Prev Row Hash */
            prev_row_hash: string;
            /** Request Id */
            request_id: string | null;
            /** Result Hash */
            result_hash: string | null;
            /** Row Hash */
            row_hash: string;
            /** Seq */
            seq: number;
            /** Trace Id */
            trace_id: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** AuditResponse */
        AuditResponse: {
            /** Entries */
            entries: components["schemas"]["AuditEntryOut"][];
            verification: components["schemas"]["AuditVerificationOut"];
        };
        /** AuditVerificationOut */
        AuditVerificationOut: {
            /** Broken At Seq */
            broken_at_seq: number | null;
            /** Checked */
            checked: number;
            /** Ok */
            ok: boolean;
            /** Reason */
            reason: string | null;
        };
        /** CaseDetailOut */
        CaseDetailOut: {
            /** Complaints */
            complaints: components["schemas"]["ComplaintOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Id */
            id: string;
            /** Notes */
            notes: string | null;
            /** Ref No */
            ref_no: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Trace Runs */
            trace_runs: components["schemas"]["TraceRunSummary"][];
            /** Typology Hint */
            typology_hint: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CaseOut */
        CaseOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Id */
            id: string;
            /** Notes */
            notes: string | null;
            /** Ref No */
            ref_no: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Typology Hint */
            typology_hint: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "open" | "in_progress" | "closed";
        /**
         * Chain
         * @enum {string}
         */
        Chain: "bitcoin" | "ethereum" | "tron" | "bnb" | "polygon" | "solana";
        /** ComplaintOut */
        ComplaintOut: {
            /** Id */
            id: string;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Source */
            source: string;
            /** Text Preview */
            text_preview: string;
        };
        /**
         * ComplaintSource
         * @enum {string}
         */
        ComplaintSource: "ncrp" | "sahyog" | "1930" | "manual";
        /** CreateCaseRequest */
        CreateCaseRequest: {
            /** Notes */
            notes?: string | null;
            /** Ref No */
            ref_no: string;
            /** Title */
            title: string;
            /** Typology Hint */
            typology_hint?: string | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Block Hash */
            block_hash?: string | null;
            /** Block Height */
            block_height?: number | null;
            /** Captured At */
            captured_at?: string | null;
            /** Provider */
            provider: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Tx Hash */
            tx_hash?: string | null;
        };
        /** GraphEdgeOut */
        GraphEdgeOut: {
            /** Asset */
            asset: string;
            /** Block Height */
            block_height: number;
            /** From */
            from: string;
            /** Taint */
            taint: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** To */
            to: string;
            /** Tx Hash */
            tx_hash: string;
            /** Value */
            value: string;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            chain: components["schemas"]["Chain"];
            /** Cluster Id */
            cluster_id: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Risk */
            risk: string | null;
            /** Typologies */
            typologies: string[];
            /** Vasp Name */
            vasp_name: string | null;
            /** Verified */
            verified: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Payload returned by the health check.
         */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Unit */
            unit: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SahyogNoticeRequest */
        SahyogNoticeRequest: {
            /** Case Ref */
            case_ref?: string | null;
            /** Legal Basis */
            legal_basis?: string | null;
            /** Requesting Officer */
            requesting_officer?: string | null;
            /**
             * Vasp Rank
             * @default 1
             */
            vasp_rank: number;
        };
        /**
         * TaintModel
         * @enum {string}
         */
        TaintModel: "haircut" | "poison";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /** Role */
            role: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TraceAccepted */
        TraceAccepted: {
            status: components["schemas"]["TraceStatus"];
            /** Stream Url */
            stream_url: string;
            /** Trace Id */
            trace_id: string;
        };
        /** TraceGraphResponse */
        TraceGraphResponse: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Trace Id */
            trace_id: string;
        };
        /** TraceParamsIn */
        TraceParamsIn: {
            /**
             * Max Hops
             * @default 8
             */
            max_hops: number;
            /**
             * Min Taint
             * @default 0.01
             */
            min_taint: number | string;
            /**
             * Min Value
             * @default 10
             */
            min_value: number | string;
            /** @default haircut */
            taint_model: components["schemas"]["TaintModel"];
        };
        /** TraceRequest */
        TraceRequest: {
            /** Address */
            address: string;
            /** Case Id */
            case_id?: string | null;
            /** @default tron */
            chain: components["schemas"]["Chain"];
            params?: components["schemas"]["TraceParamsIn"];
        };
        /** TraceResultOut */
        TraceResultOut: {
            /** Summary */
            summary: string;
            /** Trail Events */
            trail_events: components["schemas"]["TrailEventOut"][];
            /** Typologies */
            typologies: components["schemas"]["TypologyOut"][];
            /** Vasp Candidates */
            vasp_candidates: components["schemas"]["VaspCandidateOut"][];
        };
        /** TraceRunSummary */
        TraceRunSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Result Hash */
            result_hash: string | null;
            /** Start Address */
            start_address: string;
            /** Status */
            status: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * TraceStatus
         * @enum {string}
         */
        TraceStatus: "queued" | "running" | "done" | "partial" | "failed";
        /** TraceStatusResponse */
        TraceStatusResponse: {
            /** Block Heights */
            block_heights: {
                [key: string]: number;
            };
            /** Case Id */
            case_id: string | null;
            chain: components["schemas"]["Chain"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            result: components["schemas"]["TraceResultOut"] | null;
            /** Result Hash */
            result_hash: string | null;
            /** Start Address */
            start_address: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["TraceStatus"];
            /** Trace Id */
            trace_id: string;
        };
        /** TrailEventOut */
        TrailEventOut: {
            /** Address */
            address: string | null;
            /** Amount */
            amount: string | null;
            /** Asset Symbol */
            asset_symbol: string | null;
            /** Reason */
            reason: string;
            /** Timestamp */
            timestamp: string | null;
        };
        /** TypologyOut */
        TypologyOut: {
            /** Addresses */
            addresses: string[];
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Score */
            score: string;
        };
        /** UpdateCaseRequest */
        UpdateCaseRequest: {
            /** Notes */
            notes?: string | null;
            status?: components["schemas"]["CaseStatus"] | null;
            /** Title */
            title?: string | null;
            /** Typology Hint */
            typology_hint?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VaspCandidateOut */
        VaspCandidateOut: {
            /** Confidence */
            confidence: string;
            /** Confidence Terms */
            confidence_terms: {
                [key: string]: string;
            } | null;
            /** Confidence Weights */
            confidence_weights: {
                [key: string]: string;
            } | null;
            /** Deposit Address */
            deposit_address: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Hops From Seed */
            hops_from_seed: number;
            /** Label */
            label: string | null;
            /** Name */
            name: string | null;
            /** Rank */
            rank: number;
            /** Reaching Paths */
            reaching_paths: number;
            /** Signals */
            signals: string[];
            /** Source */
            source: string;
            /** Tier */
            tier: string;
            /** Verified */
            verified: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_audit_api_v1_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                action?: string | null;
                actor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"] | null;
                mine?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_v1_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_complaint_api_v1_cases__case_id__complaints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddComplaintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    start_trace_api_v1_trace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_v1_trace__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_graph_api_v1_trace__trace_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_trace__trace_id__report_get: {
        parameters: {
            query?: {
                format?: "json" | "pdf";
            };
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sahyog_notice_api_v1_trace__trace_id__sahyog_notice_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SahyogNoticeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
